artefactual/automation-tools

fixtures/vcr_cassettes/get_status_ingest.yaml, fixtures/vcr_cassettes/get_status_no_unit.yaml, fixtures/vcr_cassettes/get_status_not_json.yaml, fixtures/vcr_cassettes/get_status_transfer.yaml, fixtures/vcr_cassettes/get_status_transfer_to_ingest.yaml, transfers/transfer.py
API auth actually checks the 'username' parameter, not 'user'.
=> Automate Transfers: Fix 'user' param to 'username'

README.md, transfers/transfer.py
Add a `--hide` switch that will hide the Transfers/SIPs in Archivematica when they complete.  It will not hide units that are rejected or failed, but it will hide units that ran to completion with errors.
=> Automate Transfers: Hide units when complete

tests/test_transfers.py, transfers/transfer.py
Since there's no default get-accession-id script anymore, this shouldn't error if one doesn't exist.
=> Automate transfers: handle no accession id script

README.md, etc/transfer-script.sh, etc/transfers-2.conf, etc/transfers.conf, requirements/base.txt, transfers/models.py, transfers/transfer.py
Avoid creating log/db/pid files in the code path:
- Make models.py and transfer.py find config information in file
/etc/archivematica/automation-tools/automation-tools.conf
- Provide example config files in etc/ directory
=> transfers: add config file for log/db/pid file paths

transfers/examples/pre-transfer/add_metadata.py
add_metadata example hook writes a metadata.csv instead of a metadata.json. Not all paths correctly handle metadata.json, so this will reduce problems with other types.
=> transfers: add_metadata hook writes csv

transfers/examples/split_transfer.py
Add split_transfers script, previously at https://gist.github.com/sevein/617c12566ed3580ee566
This splits up transfers before automate transfers runs so that very large transfers can be processed automatically on smaller Archivematica pipelines.  It also splits up the contents of a `metadata.csv` file across directories.
This adds a `--metadata-only` flag that will update the metadata.csv but not move files.
=> Add split transfers script

transfers/models.py
First time you run the automation-tools, the database file need to be created.
Currently, you'll have an error saying that it is impossible to open the file.
This fix will create the file if it doesn't exist. In case it is not possible to create it (permission), the standard error (access denied) will be shown.
=> FIX creation of database

README.md, dips/atom_upload.py, etc/atom_upload_script.sh, fixtures/vcr_cassettes/deposit_fail.yaml, fixtures/vcr_cassettes/deposit_success.yaml, tests/test_atom_upload.py
Sends the DIP to the AtoM host using rsync and executes a deposit request to the
AtoM instance. A passwordless SSH connection is required to the AtoM host for the
user running this script and it must be already added to the list of known hosts.
=> Create dips.atom_upload module and scripts

README.md, etc/transfers.conf, transfers/transfer.py
The `run_scripts` function in `transfer.py` is currently very trusting in terms of what it should execute. It uses the execute bit in the file mode to determine if something is executable, and assumes it should be executed if this is set. Aside from the obvious security concern about executing user-contributed code, it also falls foul of the execution bit being set incorrectly, e.g. by some well-meaning recursive `chmod 777` etc. In particular, we have found that XML files with the executable bit set are considered for execution, which consequently fails.
This pull request improves the way that `run_scripts` works by adding a `script_extensions` whitelist that files should have before being considered executable by the code. This is configurable using the `scriptextensions` parameter in …
=> Improvement: add "whitelist" for script file extensions

fixtures/vcr_cassettes/aip2dips_dip.yaml, fixtures/vcr_cassettes/aip2dips_no_dip.yaml, fixtures/vcr_cassettes/aips2dips.yaml, fixtures/vcr_cassettes/aips_aips.yaml, fixtures/vcr_cassettes/dips_dips.yaml, transfers/amclient.py
We're sending the auth. parameters as part of the URL and they're
being returned in the next path used for the following request,
therefore, as we add them again in the next requests, they were
being sent multiple times, creating long request URLs.
The auth. should be sent in the header to avoid adding sensitive
data in the SS response but this commit avoids at least its
duplication.
The VCR cassetes have been updated to reflect the new behaviour.
=> Avoid auth. concatenation in next requests

.gitignore, requirements/base.txt, tests/test_amclient.py, tests/test_transfers.py, tox.ini, transfers/amclient.py, transfers/amclientargs.py, transfers/defaults.py, transfers/errors.py, transfers/loggingconfig.py, transfers/models.py, transfers/transfer.py, transfers/utils.py
* Creates new logging configuration script to reduce redundancy
* Separates responsibility of amclient, defaults, and cli args
* Cleans up argparse output using metavar
* Adds Conformity to PEP8 to amclient.py and transfers.py
* Returns user friendly string via getattr if function call fails in main
* Improved error return from JSON request function in amclient.py
* Adds .db and .lck files to .gitignore
* Works at module and executable level
* E402 flake8 warning ignored in Tox to enable module/exe to work
* Captures connection errors in transfers.py better
* Initial changes provides scope for future refactoring as required
* Addresses #47
Follows up https://github.com/artefactual/automation-tools/pull/46 with more appropriate naming conventions for the branch.
=> Refactors amclient.py

transfers/amclient.py, transfers/defaults.py, transfers/errors.py, transfers/loggingconfig.py, transfers/transfer.py, transfers/utils.py
The refactor in 699b018 didn't fully take into account the how logging
might work across the module. Python provides module level thread safe
logging at the module level through the logging module with appropriate
configuration.
This fix provides that functionality and additionaly sets a delay write
flag to ensure that no logs are created when there is no logging information
output.
Fixes #51
Resolves #52
Shebangs have been removed from non-executable scripts to resolve #55
Minor pylint changes added. Importantly, the incorrect check against a
non-existent ERR_AMCLIENT_UNKNOWN has been replaced with ERR_CLIENT_UNKNOWN.
--
Thanks to @sevein for his guidance on how to use the logging module effectively.
=> Allow a logger to be passed to utils as an arg

README.md, tests/test_amclient.py, tests/test_transfers.py, transfers/amclient.py, transfers/amclientargs.py, transfers/transfer.py, transfers/transfer_async.py, transfers/transferargs.py, transfers/utils.py
`transfer_async.py` is an entry point that reuses what's in `transfer.py` but hijacks the only function that needed to be changed (`start_transfer`) so the script works against the new `/api/v2beta/package` API.
`transfer_async.py` does not run `pre-transfer` scripts because the transfers are started automatically so there is no room for that. In the future, `/api/v2beta/package` may learn a new `open` status that may allow us to solve this limitation.
This can be considered a walking skeleton. The plan is to eventually have it replace `transfer.py`. The advantage is that `/api/v2beta/package` does not block. This was a priority @ JiscRDSS because you can't have a connection open for hours like we do when we're copying big transfers - `/api/v2beta/package` solves that problem.
I've been …
=> Add transfer_async

fixtures/vcr_cassettes/approve_existing_transfer.yaml, fixtures/vcr_cassettes/approve_non_existing_transfer.yaml, fixtures/vcr_cassettes/close_completed_ingests_ingests.yaml, fixtures/vcr_cassettes/close_completed_transfers_transfers.yaml, fixtures/vcr_cassettes/get_all_compressed_aips.yaml, fixtures/vcr_cassettes/get_package_details.yaml, fixtures/vcr_cassettes/get_package_details_invalid_uuid.yaml, fixtures/vcr_cassettes/ingest_status.yaml, fixtures/vcr_cassettes/ingest_status_invalid_uuid.yaml, fixtures/vcr_cassettes/pipeline.yaml, fixtures/vcr_cassettes/pipeline_none.yaml, fixtures/vcr_cassettes/reingest_exsting_aip.yaml, fixtures/vcr_cassettes/reingest_non_existing_aip.yaml, fixtures/vcr_cassettes/test_get_existing_processing_config.yaml, fixtures/vcr_cassettes/test_get_non_existing_processing_config.yaml, fixtures/vcr_cassettes/test_hide_units.yaml, fixtures/vcr_cassettes/test_transfer_approve_transfer.yaml, fixtures/vcr_cassettes/transfer_status.yaml, fixtures/vcr_cassettes/transfer_status_invalid_uuid.yaml, tests/test_amclient.py, tests/test_transfers.py, transfers/amclient.py, transfers/amclientargs.py, transfers/defaults.py, transfers/errors.py, transfers/models.py, transfers/transfer.py, transfers/utils.py
This PR adds capability to AM Client in support of the API functions
required for automated reingest.
* Adds new functions to AM Client, including reingest and transfer status.
* Provides unit testing for the additional function calls.
* Extends utils.py request mechanism to enable http authentication headers
to be set.
* A formatting issue was discovered in models.py while testing which
is now corrected.
* Warning for non-JSON responses are only output if there is a non-OK
HTTP response where responses from the API are not always JSON.
Submitted as part of Redmine ticket 11686 for CCA in support of automated reingest, cc. @timothyryanwalsh.
=> Adds AM Client Capability in support of Reingest

README.md, tests/test_transfers.py, transfers/transfer.py, transfers/transferargs.py
From PR #44, we have brought that PR into the Artefactual hosted repository, squashed the previous commits, and made some final modifications via commit 442c49f. 
@timothyryanwalsh are you happy with the final changes here? 442c49f 
* Added a note to the deletion log that a failure  might be because of the script being run remotely
* Corrected an argument being passed to `AMClient()`
* Added some minor string formatting changes to the `get_status()` function while there was an opportunity to look at the code
* Made the `--delete` flag more verbose, now `--delete-on-complete`
* Used `.get()` for dictionary look-ups to avoid potential `KeyError`
Let me know! 
Once squished again we'll close PR #44 and #75 via here.
=> Add delete-on-complete option to automation tools master branch

README.md, requirements/base.txt, tests/test_reingest.py, transfers/amclient.py, transfers/examples/reingest/reingest-cronfile, transfers/examples/reingest/run-reingest.sh, transfers/reingest.py, transfers/reingestconfig.json, transfers/reingestmodel.py, transfers/transfer.py
Creates a bulk reingest mechanism
This is a script for the Canadian Center for Architects. The purpose
is to bulk reingest AIPs in Archivematica from a single pipeline.
The script can be run using the same mechanism as others in the automation
tools repository, i.e. running a crontab task every (x) minutes. In support
of this script, PR #57 was submitted to enhance the amclient script's
capabilities.
This branch is based on the dev branch in #57 as the two sets of changes are related. The AM Client commits should be reviewed as part of #57 and this review should focus on commit 19bc9a028ddc645459e4fd82118000281759980f
cc. @timothyryanwalsh
=> CCA reingest script

fixtures/vcr_cassettes/test_call_start_transfer_endpoint.yaml, tests/test_transfer_model.py, tests/test_transfers.py, transfers/models.py, transfers/transfer.py
This PR is in support of the work being done to debug the automation-tools workflow at the University of Melbourne where a number of issues have been observed, but cannot all be pinned down accurately without automation-tools performing better. 
* We now supply the config_file argument consistently to all run_scripts functions.
* Exception handling has been made more specific to ensure tha other errors are not masked during execution.
* A post-execution hook has been implemented to clean-up the script once it has successfully exited, e.g. to ensure that the process lock pid.lck file is removed without having to explicitly make that call more than once in the code.
* The post-execution hook will also look after the session closure for the database.
* Logging has been improved where …
=> Various fixes to improve automation-tools debugging, and create more seamless execution

tests/test_transfers.py, transfers/transfer.py
The previous commit broke how the transfer path was utilised by the
script, namely, a non-absolute path was sent to the pre-transfers
scripts which saw them manipulate the automation tools folder instead
of the transfer folder. The previous functionality has been
re-implemented and tests created to demonstrate the return of a
tuple containing the transfer name and the transfer path.
Additionally, the automation-tools will verify that the transfer_path
can be discovered, because if it doesn't exist for any reasson, e.g.
the scripts are being run remotely, or have been configured
incorrectly, then we do not want to run the scripts at all.
Connected to archivematica/Issues#433
=> Correct the behavior of the transfer path

requirements/local.txt, tests/test_transfers.py, transfers/transfer.py
This PR is separated into two commits which will be squished before merging. One to demonstrate the issue reported in the original ticket. The tests will fail. We test for the values we want, not the values we're writing. 
The second commit then introduces the correct values to `transfer.py` so that the tests pass. 
archivematica/Issues#447
**NB** The reason for the additional caution i.e. the two commits is due to the regressions introduced during the previous two commits. This PR is simply a corrective one. In future, if we can refactor this function we should  be able to make the automation tools even more robust.
=> Fixes regression involving target name and introduces a new integration test

transfers/transfer.py
When we use the parameter --files with the transfers.py script  os.path.isdir returns  a false statement
I repaced it with os.path.exists and will also return True if there's a regular file with that name.
Connected to archivematica/issues#461
=> Correct the behavior of Invalid transfer path

fixtures/vcr_cassettes/get_default_locations.yaml, fixtures/vcr_cassettes/test_package_endpoint.yaml, tests/test_amclient.py, transfers/amclient.py, transfers/amclientargs.py
This PR adds three new capabilities to `amclient.py`: 
* List storage locations
* Create package
* Extract file relative to path of an AIP
Functionality has been integrated with the client, i.e. it isn't just module capability. Tests have been provided, but we might want to improve on those as the Sprints involved in this work progress. 
For the reviewer, if there are any nice-to-have's then we might consider a new issue and PR in future as this work seeks to satisfy the initial requirements of the Wellcome AMAUAT work. 
Connected to archivematica/issues#478
Connected to archivematica/issues#510
Connected to archivematica/issues#509
Examples of CLI usage below:
Most are based on DemoTransfer in the SampleData repository, UUIDs, passwords, urls, and transfer names need to be replaced …
=> Add functions required for AMAUAT black-box tests

README.md
There isn't a lot of information to describe what reingest.py is
expected to do, and how it should be monitored. We provide this
information here.
For reviewers, just one file has changed `README.md`. 
You can use the diff output if you like, but the rendered text can be viewed in the branch here: https://github.com/artefactual/automation-tools/tree/dev/issue-11686-document-reingest#reingest
Connected to archivematica/issues#300
=> Update the documentation around reingest.py

aips/create_dip.py, requirements/base.txt
Upgrading `metsrw` was not required but it's the only script using it and it works in both versions.
https://github.com/archivematica/Issues/issues/653
=> Create DIP: support PREMIS 2.2 and 3.0 namespaces

aips/create_dip.py, aips/create_dips_job.py, dips/atom_upload.py, dips/storage_service_upload.py, fixtures/vcr_cassettes/test_storage_service_upload_async_fail.yaml, fixtures/vcr_cassettes/test_storage_service_upload_request_fail.yaml, fixtures/vcr_cassettes/test_storage_service_upload_success.yaml, tests/test_atom_upload.py, tests/test_create_dip.py, tests/test_create_dips_job.py, tests/test_storage_service_upload.py
Uploads a local DIP to a DIP storage location in an SS instance.
Requires access to a pipeline's currently processing location path (the
shared path), to move the DIP folder in there and send a requests to the
Storage Service to process that DIP and create a relationship with the
AIP from where it was created.
Add METS type argument to `create_dip` script to choose between a
generated METS file that matches AtoM requirements for DIP upload and
copying the AIP's METS file directly, like the Storage Service does, to
be able to move the DIP to the SS. Defaults to AtoM METS for backwards
compatibility.
Allow to upload DIPs after creation in `create_dips_job`. Accept
different subsets of parameters and optionally upload the created DIPs
to AtoM or the Storage Service. Extend this script to …
=> Add DIP upload to SS script

README.md, aips/create_dip.py, tests/test_create_dip.py
This is connected to https://github.com/archivematica/Issues/issues/643. 
Former PR: https://github.com/artefactual/automation-tools/pull/107
This incorporates an "avalon" METS type, to fulfill the obligations of the connected issue above. In order to do this in a logical way, I also moved some of the logic out of the create_dip function and into smaller, easier-to-digest functions.
I tested the Avalon workflow as well as the Atom workflow, but testing should ensure that the new storage-service method is working fine as well.
@jraddaoui reviewed my previous PR. Radda, you had a bunch of questions that I may or may not have answered in direct message about the structure of the AIP. I'll recap briefly... Files are expected to come into Archivematica structured in a specific way, and the DIP …
=> Restructure create_dip with additional Avalon option

README.md, etc/transfer-script.sh
When using the installation instructions for the automation tools I ran into some small access related issues. Besides this I also added some small clarifications for docker users. 
For the instructions I assumed that most of the access rights should stay with the administrator. A reasonable alternative would be to make the archivematica user the owner of all automation-tools. I don't know what you guys think is best?
Fixes: archivematica/issues#729
=> Update installation instructions

etc/transfers.conf, fixtures/vcr_cassettes/test_transfer_async_api_create_package.yaml, tests/test_transfers_async.py, transfers/transfer_async.py
This pull request adds a `processingconfig` setting in the `transfers.conf` file that allows users to specify which processing configuration to use for transfers created with the `transfer_async.py` script.
`transfer_async.py` wasn't working following a refactor of `transfer.py`, so I've also fixed a few things (a character encoding issue, out-of-date function signature, and switched to using the existing helpers in the `models` module for database interactions) to enable this feature to work.
I also added an integration test for `transfer_async.py` to help prevent future breaking changes.
=> Fix transfer_async.py and add ability to specify processing config by name

.pre-commit-config.yaml, transfers/models.py
This updates the versions of the pre-commit dependencies to support Python 3.6 and fixes the URL of the flake8 repository.
Connected to https://github.com/archivematica/Issues/issues/1558
=> Update pre-commit configuration

etc/transfer-script.sh
Added missing required command-line options (Archivematica and storage
service URLs) to transfer script tempate and added backslashes so
command-line options aren't treated as separate commands.
=> Add required options to transfer script template.

.markdownlint.jsonc, .pre-commit-config.yaml, README.md
This adds `markdownlint` and `doctoc` to `pre-commit` for linting the main markdown files in the repository.
=> Lint Markdown files

.pre-commit-config.yaml, README.md, requirements-dev.txt, requirements.txt
`README.md` has been updated because its [emphasis styles](https://github.com/DavidAnson/markdownlint/blob/main/doc/md049.md) were mixing `_` and `*` characters. Detection for that has been improved in the [v0.40.0 release](https://github.com/igorshubovych/markdownlint-cli/releases/tag/v0.40.0) of `markdownlint-cli`.
=> Upgrade dependencies

.github/workflows/test.yml, .pre-commit-config.yaml, requirements-dev.txt, requirements.txt, ruff.toml, tox.ini
Connected to https://github.com/archivematica/Issues/issues/1721
=> Drop Python 3.8 support
